# Generated by Django 3.2 on 2021-05-25 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roadBuddy', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='roadbuddymodel',
            old_name='chat_id',
            new_name='update_id',
        ),
        migrations.AddField(
            model_name='roadbuddymodel',
            name='message',
            field=models.TextField(default='NA', editable=False),
        ),
    ]
