# Generated by Django 3.2 on 2021-06-30 03:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('postal_code', models.BigIntegerField()),
                ('long_address', models.TextField(max_length=6)),
                ('longtitude', models.DecimalField(decimal_places=15, max_digits=18)),
                ('latitude', models.DecimalField(decimal_places=15, max_digits=17)),
            ],
            options={
                'ordering': ['postal_code'],
            },
        ),
        migrations.CreateModel(
            name='Temp',
            fields=[
                ('user_id', models.BigIntegerField(primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.BigIntegerField(primary_key=True, serialize=False, unique=True)),
                ('first_name', models.CharField(max_length=64)),
                ('last_name', models.CharField(default='null', max_length=64)),
                ('username', models.CharField(max_length=64)),
                ('is_started', models.BooleanField(default=True)),
                ('is_planning', models.BooleanField(default=False)),
                ('latest', models.BigIntegerField()),
            ],
            options={
                'ordering': ['user_id'],
            },
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destinations', models.TextField(default=None, max_length=4000)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rbBot.user')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='PlanningSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_id', models.BigIntegerField(unique=True)),
                ('message_id', models.BigIntegerField(unique=True)),
                ('instance', models.BigIntegerField(unique=True)),
                ('message', models.TextField(max_length=4000)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rbBot.user')),
            ],
            options={
                'ordering': ['chat_id'],
            },
        ),
    ]
