# Generated by Django 3.2 on 2021-05-28 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rbBot', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Incoming',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('update_id', models.IntegerField(unique=True)),
                ('message', models.TextField(max_length=4000)),
            ],
        ),
    ]
