# Generated by Django 3.2 on 2021-06-30 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rbBot', '0002_alter_user_latest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='latest',
            field=models.BigIntegerField(default=-1),
        ),
    ]
