# Generated by Django 3.2 on 2021-06-13 07:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rbBot', '0002_incoming'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['user_id']},
        ),
    ]
