# Generated by Django 3.2 on 2021-06-30 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rbBot', '0003_alter_user_latest'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='route',
            field=models.ManyToManyField(to='rbBot.Route'),
        ),
        migrations.AlterField(
            model_name='user',
            name='latest',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
