# Generated by Django 3.2 on 2021-06-13 07:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rbBot', '0003_alter_user_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='incoming',
            options={'ordering': ['update_id']},
        ),
    ]
