# Generated by Django 3.2 on 2021-06-13 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rbBot', '0004_alter_incoming_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewUser',
            fields=[
                ('user_id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
            ],
            options={
                'ordering': ['user_id'],
            },
        ),
    ]
