# Generated by Django 3.2 on 2021-06-13 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rbBot', '0005_newuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='newuser',
            name='status',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
