# Generated by Django 3.2 on 2021-06-14 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rbBot', '0006_newuser_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='username',
            field=models.CharField(default='jello', max_length=64),
            preserve_default=False,
        ),
    ]
