# Generated by Django 3.2 on 2021-07-01 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rbBot', '0006_planningsession_session_dests'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='planningsession',
            name='session_dests',
        ),
        migrations.AddField(
            model_name='route',
            name='route_id',
            field=models.BigIntegerField(default=None),
        ),
    ]
