# Generated by Django 3.2 on 2021-07-01 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rbBot', '0007_auto_20210701_1509'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='latest',
        ),
        migrations.AddField(
            model_name='user',
            name='current_route',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
