# Generated by Django 3.2 on 2021-06-14 02:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rbBot', '0007_user_username'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='NewUser',
            new_name='NewArrival',
        ),
    ]
