# Generated by Django 3.2 on 2021-06-14 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rbBot', '0008_rename_newuser_newarrival'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newarrival',
            name='status',
        ),
    ]
