# Generated by Django 3.2 on 2021-06-14 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rbBot', '0009_remove_newarrival_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(default='null', max_length=64),
        ),
    ]
