# Generated by Django 3.2 on 2021-06-15 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rbBot', '0010_alter_user_last_name'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='NewArrival',
            new_name='Temp',
        ),
    ]
