# Generated by Django 3.2 on 2021-06-15 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rbBot', '0011_rename_newarrival_temp'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='temp',
            options={},
        ),
    ]
