# Generated by Django 3.2 on 2021-07-01 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rbBot', '0011_auto_20210702_0711'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='planning_route',
            field=models.BigIntegerField(default=0),
        ),
    ]
