# Generated by Django 3.2 on 2021-07-02 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rbBot', '0012_alter_user_planning_route'),
    ]

    operations = [
        migrations.AlterField(
            model_name='route',
            name='destinations',
            field=models.TextField(blank=True, default='{}', max_length=4000, null=True),
        ),
    ]
