# Generated by Django 3.2 on 2021-06-26 10:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rbBot', '0012_alter_temp_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Route',
            fields=[
                ('route_id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rbBot.user')),
            ],
            options={
                'ordering': ['route_id'],
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('postal_code', models.IntegerField(max_length=6)),
                ('long_address', models.TextField(max_length=6)),
                ('longtitude', models.DecimalField(decimal_places=15, max_digits=18)),
                ('latitude', models.DecimalField(decimal_places=15, max_digits=17)),
                ('route', models.ManyToManyField(to='rbBot.Route')),
            ],
            options={
                'ordering': ['postal_code'],
            },
        ),
    ]
