# Generated by Django 3.2 on 2021-06-26 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rbBot', '0013_location_route'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='postal_code',
            field=models.IntegerField(),
        ),
    ]
