# Generated by Django 3.2 on 2021-07-02 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rbBot', '0013_alter_route_destinations'),
    ]

    operations = [
        migrations.AlterField(
            model_name='route',
            name='destinations',
            field=models.TextField(default='{}', max_length=4000),
        ),
    ]
