# Generated by Django 3.2 on 2021-06-27 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rbBot', '0014_alter_location_postal_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanningSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_id', models.IntegerField(unique=True)),
                ('message_id', models.IntegerField(unique=True)),
                ('message', models.TextField(max_length=4000)),
            ],
            options={
                'ordering': ['chat_id'],
            },
        ),
        migrations.DeleteModel(
            name='Incoming',
        ),
    ]
