# Generated by Django 3.2 on 2021-06-27 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rbBot', '0015_auto_20210627_1633'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='started',
            field=models.BooleanField(default=True),
        ),
    ]
