# Generated by Django 3.2 on 2021-06-27 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rbBot', '0016_user_started'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='latest',
            field=models.IntegerField(default=True),
        ),
    ]
