# Generated by Django 3.2 on 2021-06-27 18:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rbBot', '0017_user_latest'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='started',
            new_name='is_started',
        ),
        migrations.AddField(
            model_name='planningsession',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='rbBot.user'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='is_planning',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='latest',
            field=models.IntegerField(),
        ),
    ]
