# Generated by Django 3.2 on 2021-06-27 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rbBot', '0018_auto_20210628_0248'),
    ]

    operations = [
        migrations.AddField(
            model_name='planningsession',
            name='instance',
            field=models.IntegerField(default=-1, unique=True),
            preserve_default=False,
        ),
    ]
