# Generated by Django 3.2 on 2021-07-25 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rbBot', '0019_alter_route_destinations'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_editing',
            field=models.BooleanField(default=False),
        ),
    ]
