# Generated by Django 3.2 on 2021-06-28 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rbBot', '0019_planningsession_instance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='postal_code',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='planningsession',
            name='chat_id',
            field=models.BigIntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='planningsession',
            name='instance',
            field=models.BigIntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='planningsession',
            name='message_id',
            field=models.BigIntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='route',
            name='route_id',
            field=models.BigIntegerField(primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='temp',
            name='user_id',
            field=models.BigIntegerField(primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='latest',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_id',
            field=models.BigIntegerField(primary_key=True, serialize=False, unique=True),
        ),
    ]
