# Generated by Django 3.2 on 2021-07-25 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rbBot', '0020_user_is_editing'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='key_for_dest',
            field=models.TextField(blank=True, max_length=4000, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='new_dest',
            field=models.TextField(blank=True, max_length=4000, null=True),
        ),
    ]
