# Generated by Django 3.2 on 2021-07-26 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rbBot', '0021_auto_20210726_0158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='long_address',
            field=models.TextField(max_length=4000),
        ),
    ]
